CREATE DATABASE PANADERIA;

CREATE TABLE PERMISO(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE ROL(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE ROL_PERMISO(
	ID_ROL INT NOT NULL,
	ID_PERMISO INT NOT NULL,
	PRIMARY KEY(ID_ROL, ID_PERMISO),
	FOREIGN KEY(ID_ROL) REFERENCES ROL(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_PERMISO) REFERENCES PERMISO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE USUARIO(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(40) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN ('M', 'F', '0')),
	CONTRASENA VARCHAR(250) NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	ID_ROL INT NOT NULL,
	FOREIGN KEY (ID_ROL) REFERENCES ROL(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	CI VARCHAR(10) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(40) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN ('M', 'F')),
	TELEFONO VARCHAR(10) NOT NULL
);

CREATE TABLE DIRECCION(
	ID SERIAL PRIMARY KEY,
	AVENIDA VARCHAR(20) NOT NULL,
	BARRIO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL,
	CI_CLIENTE VARCHAR(10) NOT NULL,
	FOREIGN KEY (CI_CLIENTE) REFERENCES CLIENTE(CI)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE PEDIDO(
	ID SERIAL PRIMARY KEY,
	FECHA_PEDIDO DATE NOT NULL,
	PAGADO BOOL NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	TIPO VARCHAR(10) NOT NULL,
	TOTAL DECIMAL(12, 2) NOT NULL,
	CI_CLIENTE VARCHAR(10) NOT NULL,
	FOREIGN KEY (CI_CLIENTE) REFERENCES CLIENTE(CI)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE FACTURA_INTERNA(
	ID SERIAL PRIMARY KEY,
	TOTAL DECIMAL(12, 2) NOT NULL,
	FECHA DATE NOT NULL,
	ID_USUARIO INT NOT NULL,
	CI_CLIENTE VARCHAR(10) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (CI_CLIENTE) REFERENCES CLIENTE(CI)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE CATEGORIA(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL
);

CREATE TABLE PRODUCTO(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE NOT NULL,
	PRECIO DECIMAL(12, 2) NOT NULL,
	STOCK INT NOT NULL,
	STOCK_MINIMO INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE DETALLE_FACTURA(
	ID_PRODUCTO INT NOT NULL,
	ID_FACTURA_INTERNA INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(12, 2) NOT NULL,
	TOTAL DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY(ID_PRODUCTO, ID_FACTURA_INTERNA),
	FOREIGN KEY(ID_FACTURA_INTERNA) REFERENCES FACTURA_INTERNA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE PEDIDO_PRODUCTO(
	ID_PRODUCTO INT NOT NULL,
	ID_PEDIDO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(12, 2) NOT NULL,
	TOTAL DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY(ID_PRODUCTO, ID_PEDIDO),
	FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE NOTA_SALIDA(
	ID SERIAL PRIMARY KEY,
	FECHA DATE NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL
);

CREATE TABLE DETALLE_NOTA(
	ID_PRODUCTO INT NOT NULL,
	ID_NOTA_SALIDA INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRIMARY KEY(ID_PRODUCTO, ID_NOTA_SALIDA),
	FOREIGN KEY(ID_NOTA_SALIDA) REFERENCES NOTA_SALIDA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE RECETA(
	ID SERIAL PRIMARY KEY,
	UNIDADES INT NOT NULL,
	TIEMPO TIME NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE INSUMO(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) UNIQUE NOT NULL,
	MEDIDA VARCHAR(5) NOT NULL,
	STOCK INT NOT NULL,
	STOCK_MINIMO INT NOT NULL
);

CREATE TABLE DETALLE_RECETA(
	ID_RECETA INT NOT NULL,
	ID_INSUMO INT NOT NULL,
	CANTIDAD DECIMAL(12, 2) NOT NULL,
	MEDIDA VARCHAR(5) NOT NULL,
	PRIMARY KEY(ID_RECETA, ID_INSUMO),
	FOREIGN KEY(ID_RECETA) REFERENCES RECETA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_INSUMO) REFERENCES INSUMO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE PRODUCCION(
	ID SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(60) NOT NULL,
	FECHA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	TERMINADO BOOL NOT NULL,
	ID_RECETA INT NOT NULL,
	FOREIGN KEY(ID_RECETA) REFERENCES RECETA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE PARTICIPA(
	ID_USUARIO INT NOT NULL,
	ID_PRODUCCION INT NOT NULL,
	FECHA DATE NOT NULL,
	PRIMARY KEY(ID_USUARIO, ID_PRODUCCION),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUCCION) REFERENCES PRODUCCION(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE PROVEEDOR(
	CODIGO VARCHAR(10) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(40) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN ('M', 'F')),
	TELEFONO VARCHAR(10) NOT NULL,
	ESTADO VARCHAR(15) NOT NULL,
	EMPRESA VARCHAR(40)
);

CREATE TABLE NOTA_COMPRA(
	ID SERIAL PRIMARY KEY,
	FECHA_PEDIDO DATE NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	ID_USUARIO INT NOT NULL,
	CODIGO_PROVEEDOR VARCHAR(10) NOT NULL,
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(CODIGO_PROVEEDOR) REFERENCES PROVEEDOR(CODIGO)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE COMPRA_INSUMO(
	ID_INSUMO INT NOT NULL,
	ID_NOTA_COMPRA INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(12, 2) NOT NULL,
	TOTAL DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY(ID_NOTA_COMPRA, ID_INSUMO),
	FOREIGN KEY(ID_NOTA_COMPRA) REFERENCES NOTA_COMPRA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_INSUMO) REFERENCES INSUMO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE COMPRA_PRODUCTO(
	ID_PRODUCTO INT NOT NULL,
	ID_NOTA_COMPRA INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(12, 2) NOT NULL,
	TOTAL DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY(ID_NOTA_COMPRA, ID_PRODUCTO),
	FOREIGN KEY(ID_NOTA_COMPRA) REFERENCES NOTA_COMPRA(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE BITACORA (
    ID SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    IP VARCHAR(45) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_FIN TIMESTAMP,
    HORA_INICIO TIME NOT NULL DEFAULT CURRENT_TIME,
    HORA_FIN TIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE DETALLE_BITACORA (
    ID SERIAL PRIMARY KEY,
    ID_BITACORA INT NOT NULL,
    METODO VARCHAR(10) NOT NULL,
    RUTA VARCHAR(255) NOT NULL,
    MENSAJE TEXT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_BITACORA) REFERENCES BITACORA(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
